/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    kotlin("jvm") version "1.9.20"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    implementation("io.modelcontextprotocol:kotlin-sdk:0.3.0")

    // Add these additional dependencies
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0")
    implementation("org.jetbrains.kotlinx:kotlinx-io-core:0.3.0")

    implementation("io.github.vyfor:groq-kt:0.1.0")
    implementation("io.ktor:ktor-client-okhttp:3.0.3")
    // For testing
    testImplementation(kotlin("test"))
}

application {
    mainClass.set("mcpagent.MainKt")
}
// Apply a specific Java toolchain to ease working on different environments.
//java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(21)
//    }
//}

kotlin {
    jvmToolchain(21)
}









