/*
 * This source file was generated by the Gradle 'init' task
 */
package mcpagent

class AppTest {
//    @Test fun appHasAGreeting() {
//        val classUnderTest = MainKt
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }
}
